// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhMVTATKlVrOKnTfLAL8-JwpsInWnSbxA',
    appId: '1:523725338665:web:b5bef39510cf376240c438',
    messagingSenderId: '523725338665',
    projectId: 'marriage-events-c558f',
    authDomain: 'marriage-events-c558f.firebaseapp.com',
    storageBucket: 'marriage-events-c558f.appspot.com',
    measurementId: 'G-Y10RYM1MC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC-X42cV_0JcM14SPNJFnNiC-p85mz-yc',
    appId: '1:523725338665:android:b709bfaa3773e85e40c438',
    messagingSenderId: '523725338665',
    projectId: 'marriage-events-c558f',
    storageBucket: 'marriage-events-c558f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOGa0SZf6fPHSZ7dRNCmI9XdauDBELcMM',
    appId: '1:523725338665:ios:602c1829485d03d340c438',
    messagingSenderId: '523725338665',
    projectId: 'marriage-events-c558f',
    storageBucket: 'marriage-events-c558f.appspot.com',
    iosClientId: '523725338665-8ep7p08a9sovon0lq66ti7idsekb2932.apps.googleusercontent.com',
    iosBundleId: 'com.example.marriageEvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOGa0SZf6fPHSZ7dRNCmI9XdauDBELcMM',
    appId: '1:523725338665:ios:602c1829485d03d340c438',
    messagingSenderId: '523725338665',
    projectId: 'marriage-events-c558f',
    storageBucket: 'marriage-events-c558f.appspot.com',
    iosClientId: '523725338665-8ep7p08a9sovon0lq66ti7idsekb2932.apps.googleusercontent.com',
    iosBundleId: 'com.example.marriageEvent',
  );
}
